# 配置文件

epochs: 200
num_workers: 8
batch_size: 32
model: "unet"
in_channel: 4
mid_channel: 32
out_channel: 4
fusion_flag: true
input_channels: 4
output_channels: 4
total_parms: null
early_stop_patience: 0
resume: null
loss: "DiceLoss"
loss_type: "subarea_mean"
save_max: 5
interval: 1
optimizer: "AdamW"

lr: 0.0002
wd: 0.00001
scheduler: "CosineAnnealingLR"
cosine_T_0: 10
cosine_T_mult: 2
cosine_eta_min: 1e-6
cosine_T_max: 200

reduce_patience: 3
reduce_factor: 0.9
tb: true
data_split: false

# 地址
data_root: "/root/workspace/SliceMedix/data"
train_txt: "/root/workspace/SliceMedix/data/train_paths.txt"
val_txt: "/root/workspace/SliceMedix/data/val_paths.txt"
test_txt: "/root/workspace/SliceMedix/data/test_paths.txt"

local_train: True
train_length: 1000
val_length: 200
results_root: "/root/workspace/SliceMedix/results"
commit: "debug"


